### ISSUE TITLE
Does it also use for Map<T, U>?

### ISSUE THREAD

**Issue by shinriyo** [es-shims/Object.values#10]
I installed the module.
and import `import object.values;` in my TypeScript code.

I defined `hogeNode: Map<number, HTMLInputElement | null>;`

I call `hogeNode.values()` but `Object doesn't support property or method values` happened.

**Comment by shinriyo** [comment]
or `babel-polyfill`

**Comment by ljharb** [comment]
That's because `Object.values` is a static method; individual objects don't have a `.values` method (except for arrays, and Weak/normal Maps/Sets).

Separately, `import object.values` is invalid, and `import 'object.values'` is a no-op. If you want to shim the environment, `import 'object.values/auto'`.

As for TypeScript, I don't use it, and I'm not sure how it's relevant.

Hope I answered your question!
