### ISSUE TITLE
Function.prototype.apply was called on Object.prototype.propertyIsEnumerable, which is a string and not a function

### ISSUE THREAD

**Issue by huadong** [es-shims/Object.values#20]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/2927763/103265749-43490a80-49e9-11eb-8cc2-9eab649ade8a.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/2927763/103265836-78edf380-49e9-11eb-88fa-e45634b916b5.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/2927763/103266376-6aeca280-49ea-11eb-8ef0-de4d984cccae.png">

**Comment by huadong** [comment]
> Can you elaborate? `callBound` calls `GetIntrinsic` with the string and results in a function.
> 
> Which browser is this? Do you have a stack trace? What's using `object.values`?

It's WeChat mini-program(https://developers.weixin.qq.com/miniprogram/en/dev/framework/quickstart/#About-Mini-Programs) JS enviroment. This is the debug screenshot:

![image](https://user-images.githubusercontent.com/2927763/103333380-bebdc100-4aa8-11eb-8bc7-07a48fbe3443.png)

**Comment by ljharb** [comment]
I believe this is caused by https://github.com/ljharb/get-intrinsic/issues/5 - namely, the WeChat Miniprogram environment is not a standard JavaScript environment - in other words, it violates the EcmaScript specs.

I'm going to close this in favor of that one, but I'm not sure there's a reasonable solution that doesn't involve WeChat fixing its unnecessary getter conversion of built-in data properties.

**Comment by huadong** [comment]
> I believe this is caused by [ljharb/get-intrinsic#5](https://github.com/ljharb/get-intrinsic/issues/5) - namely, the WeChat Miniprogram environment is not a standard JavaScript environment - in other words, it violates the EcmaScript specs.
> 
Got it.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/2927763/103334601-faf32080-4aac-11eb-8a50-773fa0834ba9.png">
